### ISSUE TITLE
1738B - Prefix Sum Addicts

### ISSUE THREAD

**Issue by bhagirath77** [BhagirathSarvaiya/codeforces_solutions_python#1]

**Comment by Shubh942** [comment]
Please assign this task to me.

**Comment by HoldMyCosmos** [comment]
Please assign this task to me. I have prior experience in Competetive programming, and I have also done this question with an optimized solution.

**Comment by HoldMyCosmos** [comment]
Submitted the PR with the code added. Please check it .
